# Generated by Django 2.1.7 on 2019-02-22 22:11

from django.db import migrations, models
import django_wikidata.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wd_item', django_wikidata.fields.WikidataItemField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('party', models.CharField(max_length=255)),
                ('party_wd_item', django_wikidata.fields.WikidataItemField(max_length=50)),
            ],
        ),
    ]
